### ISSUE TITLE
what is the algorithm for hashing ? How can I Match Input Password by hashed value ? 

### ISSUE THREAD

**Issue by emadpanah** [assimoes/Neo4j.AspNet.Identity#5]
Hello There,
what is the algorithm for hashing ? How can I Match Input Password by hashed value ? 

Best Regards,

**Comment by cskardon** [comment]
The password is hashed using the default AspNet.Identity PasswordHasher set in the UserManager. Outside the scope of this project, but if you *want* to use you're own hasher, I believe you can set the UserManager.PasswordHasher property, then write some Cypher to compare directly. There's no need though as the AspNet.Identity.Core stuff handles this for you.
