### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by bashanam** [assimoes/Neo4j.AspNet.Identity#6]
Why didn't you use the network power to connect users the the same "role" node ?

**Comment by cskardon** [comment]
I can't say why it wasn't originally other than the fact that Neo4jClient serializes IEnumerable<string> elements auto-magically, and so it didn't need to be done. 

However, the most recent version of the code (not in Nuget, but checked in) *does* implement Roles in this way.

(u:User)-[:IN_ROLE]->(r:Role)

Where role simply has 'Name' as a property.
